### ISSUE TITLE
Error on start  Node.js 7.2.1

### ISSUE THREAD

**Issue by Toso82** [innovate-technologies/Cast#51] opened 2016-12-10 10:47 UTC
I find your project and services so nice and i want to try to use this on my PC with nodejs  7.2.1 but give me this what is wrong?

Cast 1.0
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (C:/Users/Giacomo/Documents/Visual Studio 2015/Projects/Cast-master/intern/HTTP/server.js:8:17)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\Giacomo\Documents\Visual Studio 2015\Projects\Cast-master\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Giacomo\Documents\Visual Studio 2015\Projects\Cast-master\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

**Comment by meyskens** [comment] 2016-12-10 10:50
Seems like a duplicate of https://github.com/innovate-technologies/Cast/issues/9

**Comment by Toso82** [comment] 2016-12-10 10:56
I don't think so it not depends on file configuration. Is it compatible with latest version of node.js? this is my config.json

{
    "httpPort": 80,
    "hostname": "http://127.0.0.1",
    "apikey":"MzthT2Pk9yVFu2FQJr3ueMeUi2YhF3",
    "trustProxy":false,

    "input": {
        "SHOUTcast": 8000
    },

    "directories":{
        "Icecast":[]
    },

    "streams": [{
        "stream": "128kbps",
        "password": "password"

    }, {
        "stream": "320kbps",
        "password": "secure"
    }, {
        "stream": "live",
        "password": "live",
        "primary": true
    }]

}
Notthing special.

**Comment by meyskens** [comment] 2016-12-10 10:58
make sure to set `httpsPort` to 0, deleting it will not disable it.

**Comment by Toso82** [comment] 2016-12-10 11:15
Thanks sorry if a disturb but I do this but now:

Cast 1.0
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80

**Comment by meyskens** [comment] 2016-12-10 11:17
Port 80 can only be binded to with admin/root privileges.

**Comment by leoetlino** [comment] 2016-12-10 11:25
Or with a net bind capability to avoid unnecessary root privileges.

**Comment by Toso82** [comment] 2016-12-10 11:31
Thanks but i just try now work. I'm not so expert in nodjs this is the problem. But i like your project and service. I try to Control but i think that i must install this
https://git-scm.com/download/win

for this error

npm ERR! git clone --template=C:\Users\Giacomo\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:leoetlino/angular-route-segment.git C:\Users\Giacomo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-leoetlino-angular-route-segment-git-v2-0-4-f1f9db42: undefined

**Closed** 2016-12-10 12:09 UTC
